# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
