# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0002_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
