# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 19:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0004_auto_20161225_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
